# Generated by Django 4.1.2 on 2023-04-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grifmood', '0002_test_count_question_test_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsMin', models.IntegerField()),
                ('pointsMax', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grifmood.test')),
            ],
            options={
                'db_table': 'resultdescription',
            },
        ),
    ]
