# Generated by Django 4.1.2 on 2023-04-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grifmood', '0007_alter_resultdescription_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
