# Generated by Django 4.1.4 on 2023-05-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grifmood', '0008_resulttest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default='<function uuid1 at 0x00000000046D7D30>', max_length=500, verbose_name='uuid'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=5000)),
                ('profileReceive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileReceive', to='grifmood.profile')),
                ('profileSend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileSend', to='grifmood.profile')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profileShare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileShare', to='grifmood.profile')),
                ('profileWatching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileWatching', to='grifmood.profile')),
            ],
            options={
                'db_table': 'ConnectionProfile',
            },
        ),
    ]
