# Generated by Django 4.1.4 on 2023-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grifmood', '0009_profile_uuid_message_connectionprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default='089f89b2-f7c8-11ed-a1a2-bdfdb077e062', max_length=500, verbose_name='uuid'),
        ),
    ]
