# Generated by Django 4.1.4 on 2023-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grifmood', '0010_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default='4c72a3bd-f7d8-11ed-bd8a-bdfdb077e062', max_length=500, verbose_name='uuid'),
        ),
    ]
