# Generated by Django 4.1.4 on 2023-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grifmood', '0012_alter_profile_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default='da45ca10-f89b-11ed-b0d8-bdfdb077e062', max_length=500, verbose_name='uuid'),
        ),
    ]
